
public enum Position {
	CENTER, LEFT_TACKLE, LEFT_GUARD, RIGHT_TACKLE, RIGHT_GUARD, TIGHT_END, QUARTERBACK, HALF_BACK, FULL_BACK, WIDE_RECEIVER1, WIDE_RECEIVER2,
	LEFT_DEFENSIVE_TACKLE, RIGHT_DEFENSIVE_TACKLE, LEFT_DEFENSIVE_END, RIGHT_DEFENSIVE_END, INSIDE_LINEBACKER, MIDDLE_LINEBACKER, OUTER_LINEBACKER, LEFT_CORNER, RIGHT_CORNER, FREE_SAFETY, STRONG_SAFETY,
	KICKER, PUNTER
}
